<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="MudBlazor" Version="9.8.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="4.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Identity\Users\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\backend\src\Modules\Identity\JobWize.Modules.Identity.Contracts\JobWize.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\..\backend\src\Modules\Applications\JobWize.Modules.Applications.Contracts\JobWize.Modules.Applications.Contracts.csproj" />
    <ProjectReference Include="..\..\..\backend\src\Shared\JobWize.Shared.Contracts\JobWize.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
