<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Applications\JobWize.Modules.Applications.Contracts\JobWize.Modules.Applications.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\JobWize.Shared\JobWize.Shared.csproj" />
    <ProjectReference Include="..\JobWize.Modules.Files.Contracts\JobWize.Modules.Files.Contracts.csproj" />
  </ItemGroup>
</Project>
